spring.application.name=demo-deploy
spring.datasource.url=jdbc:postgresql://18.212.49.148:5433/dolphinscheduler?currentSchema=ufcu
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver